apiVersion: v1
kind: BuildConfig
metadata:
  name: lsteck.test-node-typescript-492
  labels:
    app: test-node-typescript-492
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/lsteck/test-node-typescript-492.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: lsteck2-dev
        - name: BRANCH
          value: master
